logDir=/home/mohamed/Desktop/DaceDS/DaceDS4energy-main/_data
definitionDirectory=/home/mohamed/Desktop/DaceDS/DaceDS4energy-main/_data
rootDir=/home/mohamed/Desktop/DaceDS/DaceDS4energy-main/_data
requestMaxAge=12343433
executablesRoot=/home/mohamed/Desktop/DaceDS/DaceDS4energy-main/_data/executables
simulatorLogFile=omnet.log
simulatorErrorLogFile=omnet_error.log


kafkaBroker=localhost:9092
schemaRegistry=http://localhost:8081
kafkaLogLevel=msg

#TOPIC_NAMES
channelOrchestration=orchestration.simulation
channelInteraction=interaction.simulation
channelProvision=provision.simulation

topicScenario=scenario
topicResult=result
topicResource=resource
topicSyncMsg=sync
topicStatusMsg=status
topicCtrlMsg=ctrl

#SUMO
defaultConf=/home/mohamed/Desktop/DaceDS/DaceDS4energy-main/SumoWrapper/resource/default/default.sumocfg
defaultTraffic=/home/mohamed/Desktop/DaceDS/DaceDS4energy-main/SumoWrapper/resource/no.rou.xml
exe=/home/mohamed/Desktop/DaceDS/sumo/bin/sumo-gui
#exe=/usr/local/bin/sumo
#exe=/usr/local/bin/sumo-gui

sumoHost=127.0.0.1
sumoPort=19234
nativeProcessingString=native

#micro
topicMicro=micro

#coSim
coSimRespForAllTag=all
#opp
OPP_TOPIC_SEND=msg.send
OPP_TOPIC_RECEIVE=msg.receive
OPP_PRODUCER_SUFFIX=oppproducer
OPP_CONSUMER_SUFFIX=oppconsumer
