//
// Generated file, do not edit! Created by nedtool 5.6 from RadioMessage.msg.
//

#ifndef __VEINS_RADIOMESSAGE_M_H
#define __VEINS_RADIOMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    #include "veins/base/utils/SimpleAddress.h"   
    #include "veins/modules/messages/BaseFrame1609_4_m.h"         // address type
    #include <map>
    #include <string>

    // STL map used as field type
    typedef std::map<std::string, std::string> Datamap;
// }}


namespace veins {

/**
 * Class generated from <tt>RadioMessage.msg:18</tt> by nedtool.
 * <pre>
 * packet RadioMessage extends BaseFrame1609_4
 * {
 *     string sender;     // who created the message
 *     string payload;    // arbitrary text payload
 *     Datamap data;       // user-defined key/value pairs
 * }
 * </pre>
 */
class RadioMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string sender;
    ::omnetpp::opp_string payload;
    Datamap data;

  private:
    void copy(const RadioMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RadioMessage&);

  public:
    RadioMessage(const char *name=nullptr, short kind=0);
    RadioMessage(const RadioMessage& other);
    virtual ~RadioMessage();
    RadioMessage& operator=(const RadioMessage& other);
    virtual RadioMessage *dup() const override {return new RadioMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
    virtual Datamap& getData();
    virtual const Datamap& getData() const {return const_cast<RadioMessage*>(this)->getData();}
    virtual void setData(const Datamap& data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RadioMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RadioMessage& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_RADIOMESSAGE_M_H

